services:
  core-backup:
    container_name: core-backup
    build:
      context: ../
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      CORE_BACKUP_CONFIG: ${CORE_BACKUP_CONFIG:-/opt/core-backup/config/core-backup.yaml}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
    volumes:
      - type: bind
        source: ${BACKUP_DATA_DIR:-/mnt/backup/core}
        target: /mnt/backup/core
    networks:
      - net-backup

networks:
  net-backup:
    external: true