services:
  core-backup:
    container_name: core-backup
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      CONFIG_PATH: ${CONFIG_PATH:-/opt/github-backup/config/github-backup.yaml}
      STORAGE_BASE_PATH: ${STORAGE_BASE_PATH:-/mnt/backups/github}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
    volumes:
      - type: bind
        source: ${BACKUP_CONFIG_DIR:-../../project-core-backup/config}
        target: /opt/github-backup/config
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_DIR:-../backups}
        target: /mnt/backups/github
