services:
  core-backup:
    container_name: core-backup
    build:
      context: ../
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      CORE_BACKUP_CONFIG: ${CORE_BACKUP_CONFIG:-/opt/core-backup/config/core-backup.yaml}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
    volumes:
      - type: bind
        source: ${BACKUP_CONFIG_DIR:-../config}
        target: /opt/core-backup/config
      - type: bind
        source: ${BACKUP_DATA_DIR:-../backups}
        target: /mnt/backup/core
